#!/bin/bash
[[ $(screen -list| grep -c 'bot_teste') == '0' ]] && {
    clear
    echo -e "\E[44;1;37m     TEST D'ACTIVATION DU BOT SSH     \E[0m"
    echo ""
    echo -ne "\n\033[1;32mRAPPORT OU JETON\033[1;37m: "; read token
    cd $HOME/BOT
    screen -dmS bot_teste ./botssh $token > /dev/null 2>&1
    clear && echo "BOT DE TEST ACTIVÉ✔️"
} || {
    screen -r -S "bot_teste" -X quit
    clear && echo "BOT DÉSACTIVÉ"
}